apiVersion: v1
kind: Service
metadata:
  name: web-app-deployment
spec:
  type: NodePort
  selector:
    app: web
  ports:
    protocol: TCP
    port: 8080 #this is the external port
    targetPort: 80 #this port must be the same with container port